name: learning about this stuff

on:
  push:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.2.0

      - name: Install dependencies
        run: npm i

      - name: Run lint
        run: npm run lint

  format:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.2.0

      - name: Install dependencies
        run: npm i

      - name: Run format
        run: npm run format

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.2.0

      - name: Install dependencies
        run: npm i

      - name: Run build
        run: npm run build

  # deploy:
  #   runs-on: ubuntu-latest

  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Set up Node.js
  #       uses: actions/setup-node@v3
  #       with:
  #         node-version: 20.2.0

  #     - name: Install dependencies
  #       run: npm i

  #     - name: Check Github User
  #       run: |
  #         git --version
  #         git config user.name 'andrei3914'
  #         git config user.email 'popandrei230@yahoo.com'
  #         git config user.name
  #         git config user.email
  #       env:
  #         GH_AUTH_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  #     - name: Run predeploy
  #       run: npm run predeploy

  #     - name: Deploy application
  #       run: npm run deploy
  #       env:
  #         DEPLOYMENT_TOKEN: ${{ secrets.DEPLOYMENT_TOKEN }}
